[package]
name = "pic32-hal"
version = "0.1.0"
authors = ["Kiffie van Haash"]
edition = "2018"

[dependencies]
vcell = "0.1.0"
nb = "0.1.1"
embedded-hal = { version = "0.2.3", features = ["unproven"] }
mips_rt = { path = "../mips-rt" }

pic32mx1xxfxxxb = { git = "https://github.com/kiffie/pic32-pac.git", optional = true }
pic32mx274fxxxb = { git = "https://github.com/kiffie/pic32-pac.git", optional = true }
pic32mx4xxfxxxh = { git = "https://github.com/kiffie/pic32-pac.git", optional = true }
