[package]
name = "pic32-hal"
version = "0.3.0"
authors = ["Kiffie van Haash"]
edition = "2018"

[dependencies]
nb = "0.1.1"
embedded-hal = { version = "0.2.3", features = ["unproven"] }
mips-mcu = "0.1.0"
mips_rt = { git = "https://github.com/kiffie/pic32-rs.git" }
usb-device = { version = "0.2.5", optional = true }
enumflags2 = "0.6.4"

[dependencies.pic32mx1xxfxxxb]
git = "https://github.com/kiffie/pic32-pac.git"
optional = true
features = ["rt"]

[dependencies.pic32mx2xxfxxxb]
git = "https://github.com/kiffie/pic32-pac.git"
optional = true
features = ["rt"]

[dependencies.pic32mx274fxxxb]
git = "https://github.com/kiffie/pic32-pac.git"
optional = true
features = ["rt"]

[dependencies.pic32mx4xxfxxxh]
git = "https://github.com/kiffie/pic32-pac.git"
optional = true
#features = ["rt"]

