[package]
name = "pic32-hal"
version = "0.1.0"
authors = ["Kiffie van Haash"]
edition = "2018"

[dependencies]
pic32mx4xxfxxxh = { git = "https://github.com/kiffie/pic32-pac.git" }
vcell = "0.1.0"
nb = "0.1.1"
embedded-hal = "0.2.2"
